
workflows:
  native-android :
    name: M2P Starter
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - script:
          ./gradlew assembleDebug
        name: Debug Build
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ktseenu97@gmail.com
          - seenu@m2pfitech.com